---
output: 
  bookdown::html_document2:
    code_folding: hide
---

```{r message = F, warning = F, results = 'hide', echo=T}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, dev = 'png', fig.path = 'figs/', dev.args = list(family = 'serif'))

library(tidyverse)
library(patchwork)
library(ggrepel)
library(scales)

pbase <- theme_bw(base_size = 12, base_family = 'serif') + 
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8), 
    axis.text.y = element_text(size = 8),
    legend.position = c(0.5, 1.1),
    # legend.title = element_blank(),
    legend.direction = 'horizontal',
    plot.margin = unit(c(4,4,0,0), "lines"),
    strip.background = element_blank(), 
    strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5), 
    panel.background = element_rect(fill = 'black')
  ) 

lnloc <- 4.5

load(file = 'data/crsdat.RData')
load(file = 'data/biodat.RData')
load(file = 'data/envdat.RData')

```

# Figures and tables {.tabset}

## Time series

```{r obsplo, fig.height = 7, fig.width = 7}
penv <- ggplot(envdat, aes(x = date, y = val, group = `Depth (m)`, color = `Depth (m)`)) + 
  geom_line() + 
  geom_point() + 
  theme_bw() + 
  facet_wrap(~var, ncol = 1, strip.position = 'left', scales = 'free_y') + 
  theme(
    strip.background = element_blank(), 
    strip.placement = 'outside', 
    axis.title = element_blank(), 
    legend.position = 'right'
  )

pbio <- biodat %>%
  filter(!grepl('^fat', var)) %>% 
  group_by(`Depth (m)`, var, date, Species) %>% 
  summarise(
    ave = mean(val, na.rm = T),
    min = quantile(val, na.rm = T, probs = 0.05),
    max = quantile(val, na.rm = T, probs = 0.95)
  ) %>% 
  ungroup

pmu <- pbio %>% 
  filter(Species %in% 'mussel')

p1 <- ggplot(pmu, aes(x = date, group = `Depth (m)`, color = `Depth (m)`)) + 
  geom_point(aes(y = ave), position = position_dodge(width = 10)) + 
  geom_errorbar(aes(ymin = min, ymax = max), width = 0, position = position_dodge(width = 10)) + 
  theme_bw() + 
  facet_wrap(~var, ncol = 1, strip.position = 'left', scales = 'free_y') + 
  theme(
    strip.background = element_blank(), 
    strip.placement = 'outside', 
    axis.title = element_blank(), 
    legend.position = 'non'
  ) + 
  ggtitle('Mussel')


psc <- pbio %>% 
  filter(Species %in% 'scallop')

p2 <- ggplot(psc, aes(x = date, group = `Depth (m)`, color = `Depth (m)`)) + 
  geom_point(aes(y = ave), position = position_dodge(width = 10)) + 
  geom_errorbar(aes(ymin = min, ymax = max), width = 0, position = position_dodge(width = 10)) + 
  theme_bw() + 
  facet_wrap(~var, ncol = 1, strip.position = 'left', scales = 'free_y') + 
  theme(
    strip.background = element_blank(), 
    strip.placement = 'outside', 
    axis.title = element_blank(), 
    legend.position = 'none'
  ) + 
  ggtitle('Scallop')

penv - (p1 + p2 + plot_layout(ncol = 1)) + plot_layout(ncol = 2)
         
```

## Correlation matrix

```{r corplo, fig.height = 9, fig.width = 9}

# outlab <- data.frame(
#   y = c(3.5, 10.5, 18.5), 
#   lab = c('Population/\nPhysiology', 'Cellular', 'Environment')
# )

toplo <- crsdat %>% 
  mutate(
    Species = case_when(
      Species == 'mussel' ~ 'Mussel', 
      Species == 'scallop' ~ 'Scallop'
    )
  ) %>% 
  unite('fct', Species, `Depth (m)`, sep = ', ') %>% 
  mutate(
    fct = factor(fct, 
                 levels = c('Mussel, 5m', 'Scallop, 5m', 'Mussel, 30m', 'Scallop, 30m'))
  )
  
labs <- levels(toplo$var1)

p1 <- ggplot(toplo) + 
  geom_tile(aes(y = var1, x = var2, fill = cor), colour = 'black') + 
  geom_text(aes(y = var1, x = var2, label = sig)) +
  # annotation_custom(grob = textGrob(label = outlab$lab[1], hjust = 0, gp = gpar(cex = 0.7)),
  #                   ymin = outlab$y[1], ymax = outlab$y[1], xmin = 22, xmax = 22) +
  # annotation_custom(grob = textGrob(label = outlab$lab[2], hjust = 0, gp = gpar(cex = 0.7)),
  #                   ymin = outlab$y[2], ymax = outlab$y[2], xmin = 22, xmax = 22) +  
  # annotation_custom(grob = textGrob(label = outlab$lab[3], hjust = 0, gp = gpar(cex = 0.7)),
  #                   ymin = outlab$y[3], ymax = outlab$y[3], xmin = 22, xmax = 22) +
  # annotation_custom(grob = textGrob(label = outlab$lab[1], hjust = 0.5, gp = gpar(cex = 0.7)),
  #                   xmin = outlab$y[1], xmax = outlab$y[1], ymin = 22.5, ymax = 22.5) +
  # annotation_custom(grob = textGrob(label = outlab$lab[2], hjust = 0.5, gp = gpar(cex = 0.7)),
  #                   xmin = outlab$y[2], xmax = outlab$y[2], ymin = 22.5, ymax = 22.5) +  
  # annotation_custom(grob = textGrob(label = outlab$lab[3], hjust = 0.5, gp = gpar(cex = 0.7)),
  #                   xmin = outlab$y[3], xmax = outlab$y[3], ymin = 22.5, ymax = 22.5) +
  pbase +
  facet_wrap(~fct, ncol = 2) +
  scale_y_discrete('', expand = c(0, 0), labels = parse(text = rev(labs))) + 
  scale_x_discrete('', expand = c(0, 0), labels = parse(text = rev(labs))) +
  scale_fill_gradient2('Correlation', low = muted("blue"), mid = "white", high = muted("green"), midpoint = 0) +
  guides(fill = guide_colourbar(barheight = 0.5, barwidth = 8, label.theme = element_text(size = 9, angle = 0))) +
  geom_hline(yintercept = lnloc, size = 1.5) +
  geom_vline(xintercept = lnloc, size = 1.5)  

p1
```

