---
output: 
  bookdown::html_document2:
    code_folding: hide
---

```{r message = F, warning = F, results = 'hide',echo=F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, dev = 'tiff', fig.path = 'figs/', dev.args = list(family = 'serif', compression = 'lzw'))

library(tidyverse)
library(patchwork)
library(ggrepel)
library(scales)

pbase <- theme_bw(base_size = 12, base_family = 'serif') + 
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8), 
    axis.text.y = element_text(size = 8),
    legend.position = c(0.5, 1.12),
    legend.direction = 'horizontal',
    plot.margin = unit(c(4,4,0,0), "lines"),
    strip.background = element_blank(), 
    strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5), 
    panel.background = element_rect(fill = 'black')
  ) 


data(crsdat)

```

# Figures and tables {.tabset}

## Correlation matrix

```{r corplo, fig.height = 6, fig.width = 7}

# outlab <- data.frame(
#   y = c(3.5, 10.5, 18.5), 
#   lab = c('Population/\nPhysiology', 'Cellular', 'Environment')
# )

toplo1 <- crsdat %>% 
  filter(`Depth (m)` == '5m') %>% 
  filter(Species == 'mussel')
labs <- levels(toplo1$var1)

p <- ggplot(toplo1) + 
  geom_tile(aes(y = var1, x = var2, fill = cor), colour = 'black') + 
  geom_text(aes(y = var1, x = var2, label = sig)) +
  # annotation_custom(grob = textGrob(label = outlab$lab[1], hjust = 0, gp = gpar(cex = 0.7)),
  #                   ymin = outlab$y[1], ymax = outlab$y[1], xmin = 22, xmax = 22) +
  # annotation_custom(grob = textGrob(label = outlab$lab[2], hjust = 0, gp = gpar(cex = 0.7)),
  #                   ymin = outlab$y[2], ymax = outlab$y[2], xmin = 22, xmax = 22) +  
  # annotation_custom(grob = textGrob(label = outlab$lab[3], hjust = 0, gp = gpar(cex = 0.7)),
  #                   ymin = outlab$y[3], ymax = outlab$y[3], xmin = 22, xmax = 22) +
  # annotation_custom(grob = textGrob(label = outlab$lab[1], hjust = 0.5, gp = gpar(cex = 0.7)),
  #                   xmin = outlab$y[1], xmax = outlab$y[1], ymin = 22.5, ymax = 22.5) +
  # annotation_custom(grob = textGrob(label = outlab$lab[2], hjust = 0.5, gp = gpar(cex = 0.7)),
  #                   xmin = outlab$y[2], xmax = outlab$y[2], ymin = 22.5, ymax = 22.5) +  
  # annotation_custom(grob = textGrob(label = outlab$lab[3], hjust = 0.5, gp = gpar(cex = 0.7)),
  #                   xmin = outlab$y[3], xmax = outlab$y[3], ymin = 22.5, ymax = 22.5) +
  pbase +
  scale_y_discrete('', expand = c(0, 0), labels = parse(text = rev(labs))) + 
  scale_x_discrete('', expand = c(0, 0), labels = parse(text = rev(labs))) +
  scale_fill_gradient2('Correlation', low = muted("blue"), mid = "white", high = muted("red"), midpoint = 0) +
  guides(fill = guide_colourbar(barheight = 0.5, barwidth = 5, label.theme = element_text(size = 6, angle = 0)))# +
  # geom_hline(yintercept = 6.5, size = 1.5) +
  # geom_hline(yintercept = 14.5, size = 1.5) +
  # geom_vline(xintercept = 6.5, size = 1.5) +
  # geom_vline(xintercept = 14.5, size = 1.5) 


```

